// Cockpit pilotes : santé 🟢🟠🔴 de chaque restaurant, invitations, retours à traiter, NPS.
import { useEffect, useState } from 'react';
import { api } from '../../lib/api';
import { PageTitle, ErrorBox, Stat } from '../../components/ui';
import { Field } from '../../components/Modal';

type Pilot = { id: string; name: string; city: string | null; founder: boolean; plan: string; dayNumber: number; status: 'vert' | 'orange' | 'rouge'; reasons: string[]; checklist: { done: number; total: number }; week: { events: number; sales: number; movements: number; orders: number }; daysSinceLogin: number | null; nps: { score: number | null } | null; openFeedback: number; members: { email: string; fullName: string; role: string }[] };
type FB = { id: string; kind: string; score: number | null; message: string | null; page: string | null; status: string; published: boolean; createdAt: string; restaurantName: string };
type D = { pilots: Pilot[]; feedback: FB[]; summary: { total: number; vert: number; orange: number; rouge: number; activeThisWeek: number; nps: number | null; npsResponses: number; founders: number; founderSeatsLeft: number }; invited: { id: string; restaurantName: string; contactName: string; email: string; inviteCode: string; invitedAt: string; restaurantId: string | null }[] };
const DOT = { vert: '🟢', orange: '🟠', rouge: '🔴' };
export default function AdminPilots() {
  const [d, setD] = useState<D | null>(null); const [err, setErr] = useState<string | null>(null); const [inv, setInv] = useState({ email: '', restaurantName: '', contactName: '', city: '' }); const [msg, setMsg] = useState<string | null>(null); const [tab, setTab] = useState<'sante' | 'retours' | 'invitations'>('sante');
  const load = () => api<D>('/admin/pilots').then(setD).catch((e) => setErr((e as Error).message));
  useEffect(() => { void load(); }, []);
  const invite = async () => { const r = await api<{ code: string; link: string; mail: string }>('/admin/pilots/invite', { method: 'POST', json: inv }); setMsg(`Code ${r.code} — e-mail ${r.mail}. Lien : ${r.link}`); setInv({ email: '', restaurantName: '', contactName: '', city: '' }); void load(); };
  const resend = async (leadId: string) => { const r = await api<{ code: string; mail: string }>('/admin/pilots/invite', { method: 'POST', json: { leadId, resend: true } }); setMsg(`Renvoyé : ${r.code} — ${r.mail}`); };
  const treat = async (id: string) => { await api(`/admin/pilots/feedback/${id}`, { method: 'PUT', json: { status: 'traite' } }); void load(); };
  // Chantier 6 (audit) — preuve sociale : publier un retour sur le site (accord écrit du pilote requis).
  const publish = async (id: string, published: boolean) => { await api(`/admin/pilots/feedback/${id}`, { method: 'PUT', json: { published } }); void load(); };
  if (err) return <ErrorBox message={err} />; if (!d) return null; const s = d.summary;
  return (
    <div className="animate-fade-up space-y-5">
      <PageTitle title="🧭 Cockpit pilotes" subtitle="Qui va bien, qui décroche, qui a besoin d’un coup de fil aujourd’hui. Rapport envoyé chaque lundi par e-mail." />
      <div className="grid grid-cols-2 gap-3 md:grid-cols-5"><Stat label="Restaurants" value={s.total} hint={`${s.founders} fondateurs · ${s.founderSeatsLeft} places`} /><Stat label="Actifs cette semaine" value={s.activeThisWeek} tone="good" /><Stat label="À rappeler 🔴" value={s.rouge} tone={s.rouge ? 'bad' : 'default'} /><Stat label="À surveiller 🟠" value={s.orange} tone={s.orange ? 'warn' : 'default'} /><Stat label="NPS" value={s.nps === null ? '—' : s.nps} hint={`${s.npsResponses} réponse(s)`} /></div>
      <nav className="flex gap-1 rounded-2xl bg-stone-100 p-1 text-sm font-semibold">{([['sante', 'Santé'], ['retours', `Retours (${d.feedback.filter((f) => f.status === 'nouveau' && f.kind !== 'nps').length})`], ['invitations', 'Invitations']] as const).map(([k, l]) => <button key={k} onClick={() => setTab(k)} className={`rounded-xl px-3 py-2 ${tab === k ? 'bg-white shadow-sm text-brand-800' : 'text-stone-600'}`}>{l}</button>)}</nav>
      {tab === 'sante' && <div className="space-y-2">{[...d.pilots].sort((a, b) => ['rouge', 'orange', 'vert'].indexOf(a.status) - ['rouge', 'orange', 'vert'].indexOf(b.status)).map((p) => (
        <div key={p.id} className="card flex flex-wrap items-center justify-between gap-3">
          <div><p className="font-bold">{DOT[p.status]} {p.name} <span className="text-xs font-normal text-stone-500">{p.city} · J{p.dayNumber} · {p.plan}{p.founder ? ' · fondateur' : ''}</span></p><p className="text-sm text-stone-600">{p.reasons.length ? p.reasons.join(' · ') : 'Tout va bien'}</p><p className="text-xs text-stone-400">{p.members.map((m) => `${m.fullName} <${m.email}>`).join(', ')}</p></div>
          <div className="flex gap-4 text-center text-xs text-stone-500"><div><p className="text-lg font-extrabold text-stone-900">{p.checklist.done}/{p.checklist.total}</p>checklist</div><div><p className="text-lg font-extrabold text-stone-900">{p.week.sales}</p>ventes 7 j</div><div><p className="text-lg font-extrabold text-stone-900">{p.week.movements}</p>mvts stock</div><div><p className="text-lg font-extrabold text-stone-900">{p.week.orders}</p>commandes</div><div><p className="text-lg font-extrabold text-stone-900">{p.nps?.score ?? '—'}</p>NPS</div><div><p className="text-lg font-extrabold text-stone-900">{p.daysSinceLogin ?? '∞'}</p>j sans login</div></div>
        </div>))}</div>}
      {tab === 'retours' && <div className="space-y-2">{d.feedback.map((f) => <div key={f.id} className={`card flex items-start justify-between gap-3 ${f.status === 'traite' ? 'opacity-50' : ''}`}><div><p className="text-sm"><b>{f.restaurantName}</b> · {f.kind === 'nps' ? `NPS ${f.score}/10` : f.kind} · <span className="text-stone-400">{new Date(f.createdAt).toLocaleString('fr-FR')} · {f.page}</span>{f.published && <span className="ml-2 rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] font-semibold text-emerald-700"> Publié sur le site</span>}</p><p className="mt-1">{f.message ?? <i className="text-stone-400">sans message</i>}</p></div><div className="flex flex-col gap-2 shrink-0">{f.kind === 'nps' && f.message && <button className="btn-ghost text-xs" title="Publier sur le site uniquement avec l’accord écrit du pilote" onClick={() => void publish(f.id, !f.published)}>{f.published ? 'Retirer du site' : 'Publier (accord pilote)'}</button>}{f.status === 'nouveau' && f.kind !== 'nps' && <button className="btn-ghost" onClick={() => void treat(f.id)}>Traité</button>}</div></div>)}{!d.feedback.length && <p className="text-stone-500">Aucun retour pour l’instant.</p>}</div>}
      {tab === 'invitations' && <div className="space-y-4">
        <div className="card space-y-3"><h2 className="font-bold">Inviter un restaurant pilote</h2><p className="text-sm text-stone-600">Il reçoit un e-mail avec son code et un lien d’inscription pré-rempli ; à l’inscription il devient fondateur (−50 % à vie).</p>
          <div className="grid gap-2 sm:grid-cols-4"><Field label="Restaurant"><input className="input" value={inv.restaurantName} onChange={(e) => setInv({ ...inv, restaurantName: e.target.value })} /></Field><Field label="Contact"><input className="input" value={inv.contactName} onChange={(e) => setInv({ ...inv, contactName: e.target.value })} /></Field><Field label="E-mail"><input className="input" type="email" value={inv.email} onChange={(e) => setInv({ ...inv, email: e.target.value })} /></Field><Field label="Ville"><input className="input" value={inv.city} onChange={(e) => setInv({ ...inv, city: e.target.value })} /></Field></div>
          <button className="btn-primary" disabled={!inv.email || !inv.restaurantName || !inv.contactName} onClick={() => void invite()}>Envoyer l’invitation</button>{msg && <p className="break-all text-sm text-brand-900">{msg}</p>}</div>
        <div className="card overflow-x-auto p-0"><table className="w-full text-sm"><thead className="bg-stone-50 text-left text-xs uppercase text-stone-500"><tr><th className="p-3">Restaurant</th><th className="p-3">Contact</th><th className="p-3">Code</th><th className="p-3">Invité le</th><th className="p-3">État</th></tr></thead><tbody className="divide-y divide-stone-100">{d.invited.map((i) => <tr key={i.id}><td className="p-3 font-semibold">{i.restaurantName}</td><td className="p-3">{i.contactName}<br /><span className="text-xs text-stone-500">{i.email}</span></td><td className="p-3 font-mono">{i.inviteCode}</td><td className="p-3">{new Date(i.invitedAt).toLocaleDateString('fr-FR')}</td><td className="p-3">{i.restaurantId ? '✅ inscrit' : <button className="text-xs underline" onClick={() => void resend(i.id)}>en attente · renvoyer</button>}</td></tr>)}</tbody></table></div>
      </div>}
    </div>
  );
}
