// Chantier 17 — Tableau de bord fondateur : la plateforme entière en un écran.
import { Link } from 'react-router-dom';
import { AlertTriangle, CheckCircle2, Info, ArrowRight } from 'lucide-react';
import { useApi } from '../../lib/useApi';
import { PageTitle, Loader, ErrorBox } from '../../components/ui';

type Num = Record<string, number>;
type D = { users: Num; restaurants: Num; vendors: Num; offers: Num; products: Num; orders: Num; commissions: Num; leads: Num; weekly: { week: string; all: number; mkt: number; gmv: number }[]; signups: { week: string; c: number }[]; prospects: { kind: string; status: string; c: number }[]; demandTop: { name: string; restaurants: number; covered: boolean }[]; topVendors: { name: string; city: string | null; status: string; offers: number; orders: number; gmv: number; linked: number }[]; topRestaurants: { name: string; city: string | null; plan: string; createdAt: string; orders: number; items: number; suppliers: number; lastOrder: string | null }[]; recent: { id: string; at: string; actorEmail: string | null; action: string; target: string | null; meta: Record<string, unknown> | null }[]; recentOrders: { id: string; reference: string; status: string; total: number; createdAt: string; restaurant: string; vendor: string | null }[]; env: { adminEmails: boolean; llm: boolean; stripe: boolean; resend: boolean; appUrl: string | null; vendorAutoApprove: boolean }; todo: { level: string; text: string; to: string | null }[] };
const eur = (v: number) => `${Number(v).toFixed(0)} €`;
const ago = (iso: string | null) => { if (!iso) return '—'; const d = Math.round((Date.now() - new Date(iso).getTime()) / 86400000); return d === 0 ? 'aujourd’hui' : `il y a ${d} j`; };
const ACTION: Record<string, string> = { 'vendor.register': 'Inscription grossiste', 'vendor.catalog_import': 'Import catalogue', 'prospect.invite_vendor': 'Invitation grossiste', 'reference.create': 'Produit créé', 'reference.update': 'Produit modifié', 'reference.merge': 'Fusion produits', 'account.export': 'Export compte', 'account.delete': 'Suppression compte', 'login.failed': 'Échec connexion' };

function Kpi({ label, value, sub, tone }: { label: string; value: string | number; sub?: string; tone?: 'good' | 'bad' | 'warn' }) {
  return <div className="card !p-3"><p className="text-xs text-stone-500">{label}</p><p className={`text-2xl font-extrabold ${tone === 'good' ? 'text-emerald-700' : tone === 'bad' ? 'text-red-700' : tone === 'warn' ? 'text-amber-700' : ''}`}>{value}</p>{sub && <p className="text-xs text-stone-500">{sub}</p>}</div>;
}
function Bars({ data, label }: { data: { k: string; v: number; v2?: number }[]; label: (d: { k: string; v: number; v2?: number }) => string }) {
  const max = Math.max(1, ...data.map((d) => d.v));
  return <div className="flex h-28 items-end gap-1">{data.map((d) => <div key={d.k} className="group relative flex flex-1 flex-col items-center justify-end" title={label(d)}><div className="w-full rounded-t bg-stone-200" style={{ height: `${Math.max(2, 100 * d.v / max)}%` }}>{d.v2 !== undefined && d.v > 0 && <div className="w-full rounded-t bg-brand-500" style={{ height: `${100 * d.v2 / d.v}%` }} />}</div><span className="mt-1 text-[9px] text-stone-400">{d.k.slice(5)}</span></div>)}</div>;
}

export default function AdminDashboard() {
  const { data: d, loading, error } = useApi<D>('/admin/dashboard');
  if (loading) return <Loader />; if (error) return <ErrorBox message={error} />; if (!d) return null;
  const weeks = [...Array(12)].map((_, i) => { const dt = new Date(); dt.setDate(dt.getDate() - dt.getDay() + 1 - 7 * (11 - i)); return dt.toISOString().slice(0, 10); });
  const wk = (k: string) => d.weekly.find((w) => w.week === k); const su = (k: string) => d.signups.find((w) => w.week === k)?.c ?? 0;
  const pros = (kind: string) => { const rows = d.prospects.filter((p) => p.kind === kind); const tot = rows.reduce((a, r) => a + r.c, 0); const g = (s: string) => rows.find((r) => r.status === s)?.c ?? 0; return { tot, contacte: g('contacte') + g('rdv') + g('interesse'), converti: g('converti'), perdu: g('perdu') }; };
  const pr = pros('restaurant'), pf = pros('fournisseur'); const acceptPct = d.orders.mkt ? Math.round(100 * (d.orders.mkt - d.orders.refused) / d.orders.mkt) : null;
  const coveredPct = d.products.tracked ? Math.round(100 * d.offers.productsCovered / d.products.tracked) : 0;
  return (
    <div className="animate-fade-up space-y-6">
      <PageTitle title="🎛️ Tableau de bord AFRISUPPLY" subtitle="Offre, demande, activité, argent, pipeline — tout en un écran. Actualisé à chaque ouverture." />

      {d.todo.length > 0 && <section className="space-y-2">{d.todo.map((t, i) => { const Icon = t.level === 'critical' ? AlertTriangle : t.level === 'action' ? CheckCircle2 : Info; const cls = t.level === 'critical' ? 'border-red-200 bg-red-50 text-red-900' : t.level === 'action' ? 'border-amber-200 bg-amber-50 text-amber-900' : t.level === 'watch' ? 'border-blue-200 bg-blue-50 text-blue-900' : 'border-stone-200 bg-stone-50 text-stone-700'; return <div key={i} className={`flex items-center justify-between gap-3 rounded-xl border p-3 text-sm ${cls}`}><span className="flex items-center gap-2"><Icon size={16} /> {t.text}</span>{t.to && <Link to={t.to} className="flex items-center gap-1 font-semibold">Ouvrir <ArrowRight size={14} /></Link>}</div>; })}</section>}

      <section><h2 className="mb-2 font-bold">Demande — restaurants</h2><div className="grid grid-cols-2 gap-3 md:grid-cols-5">
        <Kpi label="Restaurants inscrits" value={d.restaurants.total} sub={`+${d.restaurants.m} sur 30 j`} /><Kpi label="Actifs (commande < 30 j)" value={d.restaurants.active30} tone={d.restaurants.active30 ? 'good' : undefined} /><Kpi label="En essai / payants" value={`${d.restaurants.trial} / ${d.restaurants.paying}`} /><Kpi label="Utilisateurs" value={d.users.total} sub={`+${d.users.w} cette semaine`} /><Kpi label="Produits suivis (distincts)" value={d.products.tracked} sub={`${d.products.priv} produits privés créés`} />
      </div></section>

      <section><h2 className="mb-2 font-bold">Offre — grossistes</h2><div className="grid grid-cols-2 gap-3 md:grid-cols-5">
        <Kpi label="Grossistes actifs" value={d.vendors.actif} tone={d.vendors.actif ? 'good' : 'bad'} sub={d.vendors.attente ? `${d.vendors.attente} en attente` : 'aucun en attente'} /><Kpi label="Offres en ligne" value={d.offers.inStock} sub={`${d.offers.offers} au total`} /><Kpi label="Produits couverts" value={d.offers.productsCovered} sub={`sur ${d.products.ref} du référentiel`} /><Kpi label="Couverture de la demande" value={`${coveredPct} %`} tone={coveredPct > 50 ? 'good' : coveredPct > 0 ? 'warn' : 'bad'} sub="produits suivis ayant ≥ 1 offre" /><Kpi label="Demandes vitrine" value={d.leads.vitrine} sub="clics « Me prévenir »" />
      </div></section>

      <section><h2 className="mb-2 font-bold">Activité & argent</h2><div className="grid grid-cols-2 gap-3 md:grid-cols-5">
        <Kpi label="Commandes marketplace 30 j" value={d.orders.mktM} sub={`${d.orders.m} toutes sources`} /><Kpi label="Volume d'affaires 30 j" value={eur(d.orders.gmvM)} sub={`${eur(d.orders.gmvAll)} cumulé`} /><Kpi label="Taux d'acceptation" value={acceptPct === null ? '—' : `${acceptPct} %`} sub={d.orders.avgDecisionH ? `réponse moyenne ${Number(d.orders.avgDecisionH).toFixed(1)} h` : ''} /><Kpi label="Commissions du mois" value={eur(d.commissions.month)} sub={`${eur(d.commissions.uninvoiced)} non facturées`} tone={d.commissions.month ? 'good' : undefined} /><Kpi label="En attente grossiste" value={d.orders.pending} tone={d.orders.pending ? 'warn' : undefined} />
      </div></section>

      <div className="grid gap-4 lg:grid-cols-2">
        <section className="card"><h3 className="font-bold">Commandes par semaine <span className="text-xs font-normal text-stone-500">(gris : toutes · orange : marketplace)</span></h3><div className="mt-3"><Bars data={weeks.map((k) => ({ k, v: wk(k)?.all ?? 0, v2: wk(k)?.mkt ?? 0 }))} label={(x) => `${x.v} commandes, ${x.v2} marketplace`} /></div></section>
        <section className="card"><h3 className="font-bold">Inscriptions restaurants par semaine</h3><div className="mt-3"><Bars data={weeks.map((k) => ({ k, v: su(k) }))} label={(x) => `${x.v} inscription(s)`} /></div></section>
      </div>

      <section className="card"><h3 className="font-bold">Pipeline prospection</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">
        {[['Restaurants', pr, '/app/admin/prospection'], ['Grossistes', pf, '/app/admin/prospection']].map(([l, p, to]) => { const x = p as typeof pr; return <Link key={l as string} to={to as string} className="rounded-xl bg-stone-50 p-3 text-sm hover:bg-stone-100"><p className="font-semibold">{l as string} — {x.tot} fiches</p><div className="mt-2 flex h-3 overflow-hidden rounded-full bg-stone-200"><div className="bg-blue-400" style={{ width: `${100 * x.contacte / Math.max(1, x.tot)}%` }} /><div className="bg-emerald-500" style={{ width: `${100 * x.converti / Math.max(1, x.tot)}%` }} /><div className="bg-red-300" style={{ width: `${100 * x.perdu / Math.max(1, x.tot)}%` }} /></div><p className="mt-1 text-xs text-stone-500">{x.contacte} en cours · <b className="text-emerald-700">{x.converti} convertis</b> · {x.perdu} perdus · {x.tot - x.contacte - x.converti - x.perdu} à contacter</p></Link>; })}
      </div></section>

      <div className="grid gap-4 lg:grid-cols-2">
        <section className="card !p-0"><h3 className="p-4 pb-2 font-bold">Produits les plus suivis par les restaurants</h3><table className="w-full text-sm"><tbody className="divide-y divide-stone-100">{d.demandTop.map((p) => <tr key={p.name}><td className="px-4 py-2">{p.name}</td><td className="px-4 py-2 text-right text-stone-500">{p.restaurants} resto{p.restaurants > 1 ? 's' : ''}</td><td className="px-4 py-2 text-right">{p.covered ? <span className="pill bg-emerald-50 text-emerald-800">offre ✓</span> : <span className="pill bg-red-50 text-red-800">aucune offre</span>}</td></tr>)}</tbody></table>{!d.demandTop.length && <p className="p-4 text-sm text-stone-500">Aucun stock suivi.</p>}</section>
        <section className="card !p-0"><h3 className="p-4 pb-2 font-bold">Grossistes</h3><table className="w-full text-sm"><thead className="bg-stone-50 text-left text-xs uppercase text-stone-500"><tr><th className="px-4 py-2">Nom</th><th className="px-4 py-2 text-right">Offres</th><th className="px-4 py-2 text-right">Cdes</th><th className="px-4 py-2 text-right">Volume</th><th className="px-4 py-2 text-right">Liés</th></tr></thead><tbody className="divide-y divide-stone-100">{d.topVendors.map((v) => <tr key={v.name}><td className="px-4 py-2"><p className="font-semibold">{v.name}</p><p className="text-xs text-stone-500">{v.city ?? ''} · {v.status}</p></td><td className="px-4 py-2 text-right">{v.offers}</td><td className="px-4 py-2 text-right">{v.orders}</td><td className="px-4 py-2 text-right">{eur(v.gmv)}</td><td className="px-4 py-2 text-right">{v.linked}</td></tr>)}</tbody></table>{!d.topVendors.length && <p className="p-4 text-sm text-stone-500">Aucun grossiste inscrit. <Link className="underline" to="/app/admin/prospection">Inviter</Link>.</p>}</section>
      </div>

      <section className="card !p-0"><h3 className="p-4 pb-2 font-bold">Restaurants (15 derniers)</h3><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-stone-50 text-left text-xs uppercase text-stone-500"><tr><th className="px-4 py-2">Restaurant</th><th className="px-4 py-2">Plan</th><th className="px-4 py-2 text-right">Produits</th><th className="px-4 py-2 text-right">Fournisseurs</th><th className="px-4 py-2 text-right">Commandes</th><th className="px-4 py-2 text-right">Dernière cde</th><th className="px-4 py-2 text-right">Inscrit</th></tr></thead><tbody className="divide-y divide-stone-100">{d.topRestaurants.map((r) => <tr key={r.name + r.createdAt}><td className="px-4 py-2"><p className="font-semibold">{r.name}</p><p className="text-xs text-stone-500">{r.city ?? ''}</p></td><td className="px-4 py-2"><span className="pill bg-stone-100 text-stone-700">{r.plan}</span></td><td className="px-4 py-2 text-right">{r.items}</td><td className="px-4 py-2 text-right">{r.suppliers}</td><td className="px-4 py-2 text-right">{r.orders}</td><td className="px-4 py-2 text-right text-xs">{ago(r.lastOrder)}</td><td className="px-4 py-2 text-right text-xs">{ago(r.createdAt)}</td></tr>)}</tbody></table></div></section>

      <div className="grid gap-4 lg:grid-cols-2">
        <section className="card !p-0"><h3 className="p-4 pb-2 font-bold">Dernières commandes</h3><table className="w-full text-sm"><tbody className="divide-y divide-stone-100">{d.recentOrders.map((o) => <tr key={o.id}><td className="px-4 py-2"><p className="font-semibold">{o.reference}</p><p className="text-xs text-stone-500">{o.restaurant} → {o.vendor ?? 'fournisseur privé'}</p></td><td className="px-4 py-2 text-xs">{o.status}</td><td className="px-4 py-2 text-right font-semibold">{eur(o.total)}</td><td className="px-4 py-2 text-right text-xs text-stone-500">{ago(o.createdAt)}</td></tr>)}</tbody></table></section>
        <section className="card !p-0"><h3 className="p-4 pb-2 font-bold">Journal d’activité</h3><ul className="divide-y divide-stone-100 text-sm">{d.recent.map((a) => <li key={a.id} className="flex justify-between gap-2 px-4 py-2"><span><b>{ACTION[a.action] ?? a.action}</b> <span className="text-stone-500">{a.actorEmail ?? ''}{a.meta && 'name' in a.meta ? ` · ${String(a.meta.name)}` : ''}</span></span><span className="shrink-0 text-xs text-stone-400">{new Date(a.at).toLocaleString('fr-FR', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' })}</span></li>)}</ul></section>
      </div>

      <section className="card"><h3 className="font-bold">Configuration de la plateforme</h3><div className="mt-2 flex flex-wrap gap-2 text-xs">{[['ADMIN_EMAILS', d.env.adminEmails], ['E-mails (Resend)', d.env.resend], ['IA (LLM_API_KEY)', d.env.llm], ['Stripe', d.env.stripe], ['Auto-validation grossistes', d.env.vendorAutoApprove]].map(([l, ok]) => <span key={l as string} className={`pill ${ok ? 'bg-emerald-50 text-emerald-800' : 'bg-stone-100 text-stone-500'}`}>{ok ? '✓' : '✗'} {l as string}</span>)}<span className="pill bg-stone-100 text-stone-600">APP_URL : {d.env.appUrl ?? 'non défini'}</span></div></section>
    </div>
  );
}
